spring:
  application:
      name: wallet-app
  mvc:
    servlet:
      path: /api/v1
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password: sa